const PLAYERVIEW_ROUTE = "/player"
const EDITOR_ROUTE = "/editor"
const MAINPAGE_ROUTE = "/"

const MIN_WIDTH = 670
const MIN_NOTEBOOK_WIDTH = 1000
const MEDIUM_NOTEBOOK_WIDTH = 1200
const MIN_WIDTH_SCALE = 0.5
const MIN_NOTEBOOK_SCALE = 0.6
const MEDIUM_NOTEBOOK_SCALE = 0.75
const DEFAULT_SCALE = 1

const MAC = 'MAC'
const UNDO_HOTKEY_ENGLISH = 'z'
const UNDO_HOTKEY_RUSSIAN = 'я'
const REDO_HOTKEY_ENGLISH = 'y'
const REDO_HOTKEY_RUSSIAN = 'н'
const KEYDOWN_KEY= 'keydown'
const DELETE = "Delete"
const ENTER =  "Enter"

const WORKSPACE = "WorkSpace"
const BLACK_COLOR = "#000000"
const WHITE_COLOR = "#ffffff"

const REQUIRED_PARAMETR = 'Query parameter is required'
const NETWORK_RESPONSE = 'Network response was not ok'
const UNKNOW_TYPE = "Unknown type"
const ACCESS_KEY = 'J5T8HbG2s9h2Pq050okm_dekP6b0jI_0FdGe3YlHKOU'

const SLIDELIST = "SlideList"
const MIN_SLIDELIST_SCALE = 0.05
const MIN_NOTEBOOK_SLIDELIST_SCALE = 0.1
const MEDIUM_SLIDELIST_SCALE = 0.15
const SLIDE_PREVIEW_SCALE = 0.2
const ARROW_DOWN_KEY = "ArrowDown"
const ARROW_UP_KEY = "ArrowUp"

const SLIDE_WIDTH = 850;
const SLIDE_HEIGHT = 525;
const PLAYER_SLIDE_WIDTH = 1112;
const PLAYER_SLIDE_HEIGHT = 617;
const SLIDE_DOWNLOAD_PREVIEW_SCALE = 0.7
const RESIZE_SCALE = "resize"

export { 
    MIN_WIDTH, MIN_WIDTH_SCALE, MIN_NOTEBOOK_SCALE, MIN_NOTEBOOK_WIDTH, MEDIUM_NOTEBOOK_SCALE, MEDIUM_NOTEBOOK_WIDTH, DEFAULT_SCALE,
    MAC, UNDO_HOTKEY_ENGLISH, UNDO_HOTKEY_RUSSIAN, REDO_HOTKEY_ENGLISH, REDO_HOTKEY_RUSSIAN, KEYDOWN_KEY, DELETE, WORKSPACE, BLACK_COLOR, WHITE_COLOR, 
    ACCESS_KEY, REQUIRED_PARAMETR, NETWORK_RESPONSE, PLAYERVIEW_ROUTE, EDITOR_ROUTE, MAINPAGE_ROUTE,
    SLIDELIST, SLIDE_PREVIEW_SCALE, ARROW_DOWN_KEY, ARROW_UP_KEY, MIN_SLIDELIST_SCALE, MIN_NOTEBOOK_SLIDELIST_SCALE, MEDIUM_SLIDELIST_SCALE,
    SLIDE_WIDTH, SLIDE_HEIGHT, PLAYER_SLIDE_WIDTH, PLAYER_SLIDE_HEIGHT, UNKNOW_TYPE, SLIDE_DOWNLOAD_PREVIEW_SCALE, RESIZE_SCALE, ENTER
 }